# Generated by Django 4.0.5 on 2022-06-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.TextField()),
                ('pictureURL', models.ImageField(upload_to='photos/cardStyles/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('count', models.IntegerField()),
                ('ready', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('styleID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TimeManage.cardstyles')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TimeManage.users')),
            ],
        ),
    ]
