# Generated by Django 4.0.5 on 2022-06-17 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeManage.cardstyles')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeManage.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='laboratories',
            name='styleID',
        ),
        migrations.RemoveField(
            model_name='laboratories',
            name='userID',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
