# Generated by Django 4.0.5 on 2022-06-17 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0002_profile_relations_remove_laboratories_styleid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='relations',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeManage.user'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
