# Generated by Django 4.0.5 on 2022-06-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0004_alter_user_managers_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
