# Generated by Django 4.0.5 on 2022-06-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0006_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
