# Generated by Django 4.0.5 on 2022-06-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0007_remove_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='labID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TimeManage.laboratories'),
        ),
    ]
