# Generated by Django 4.0.5 on 2022-08-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0008_relations_labid'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratories',
            name='countOfReady',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='ready',
            field=models.TextField(),
        ),
    ]
