# Generated by Django 4.0.5 on 2022-08-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0010_alter_laboratories_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratories',
            name='ready',
            field=models.JSONField(default='dict'),
        ),
    ]
