# Generated by Django 4.0.5 on 2022-08-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0018_laboratories_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratories',
            name='deadline',
            field=models.DateField(),
        ),
    ]
