# Generated by Django 4.0.5 on 2022-08-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0019_alter_laboratories_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='ready',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TimeManage.readytasks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='ready',
            field=models.IntegerField(default=0),
        ),
    ]
