# Generated by Django 4.0.5 on 2022-08-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0020_relations_ready_alter_laboratories_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='ready',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TimeManage.readytasks'),
        ),
    ]
