# Generated by Django 4.0.5 on 2022-08-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0022_alter_relations_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relations',
            name='ready',
        ),
    ]
