# Generated by Django 4.0.5 on 2022-08-29 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManage', '0024_alter_readytasks_ready_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readytasks',
            name='ready_date',
            field=models.DateField(default=datetime.date(2022, 8, 29)),
        ),
    ]
